 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: nginx
   annotations:
     ingress.kubernetes.io/ssl-redirect: "false"
 spec:
   defaultBackend:
     service:
        name: nginx
        port:
           number: 8080
 EOF
