apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello World
  labels:
    app: Hello World
spec:
  selector:
    matchLabels:
      app: Hello World
  template:
    metadata:
      labels:
        app: Hello World
    spec:
      containers:
      - name: Hello World
        image: srikavyapendiala/Hello World
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
