apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: ClusterIP
  ports:
  - port: 1809
    targetPort: 1809
    protocol: TCP
    name: http
  selector:
    app: hello
